#!/usr/bin/env python3
"""
Face Embedding Test
Tests face embedding functionality with hardcoded name.
"""

import requests
import json
import numpy as np
import time
from datetime import datetime

def generate_dummy_embedding():
    """Generate a dummy 128-dimensional face embedding (face-api.js format)."""
    # In a real implementation, this would be generated by face-api.js
    return [round(float(i)/100, 3) for i in range(128)]

def test_face_embedding():
    """Test face embedding functionality with hardcoded name."""
    # Hardcoded person information
    person_name = "Dakkkiiieee"
    person_id = f"unknown_{int(datetime.now().timestamp() * 1000)}"
    relationship = "Test Person"
    
    print(f"=== Face Embedding Test ===")
    print(f"Person Name: {person_name}")
    print(f"Person ID: {person_id}")
    print(f"Relationship: {relationship}")
    print("")
    
    base_url = "http://localhost:8000"
    
    # Step 1: Create person record
    print("1. Creating person record...")
    person_data = {
        "person_id": person_id,
        "name": "Unknown Person",
        "relationship": "Unknown",
        "aggregated_context": "Recently detected unknown person",
        "cached_description": "Recently detected unknown person"
    }
    
    try:
        response = requests.post(f"{base_url}/person", json=person_data)
        if response.status_code == 200:
            print("✅ Person record created successfully")
        else:
            print(f"❌ Failed to create person record: {response.status_code}")
            print(f"   Error: {response.text}")
            return False
    except Exception as e:
        print(f"❌ Error creating person record: {e}")
        return False
    
    # Step 2: Update person with real information
    print("\n2. Updating person information...")
    update_data = {
        "name": person_name,
        "relationship": relationship,
        "aggregated_context": f"Identified as {person_name}",
        "cached_description": f"Identified as {person_name}"
    }
    
    try:
        response = requests.put(f"{base_url}/person/{person_id}", json=update_data)
        if response.status_code == 200:
            updated_person = response.json()
            print("✅ Person information updated successfully")
            print(f"   Name: {updated_person['name']}")
            print(f"   Relationship: {updated_person['relationship']}")
        else:
            print(f"❌ Failed to update person information: {response.status_code}")
            print(f"   Error: {response.text}")
            return False
    except Exception as e:
        print(f"❌ Error updating person information: {e}")
        return False
    
    # Step 3: Send face embedding to backend
    print("\n3. Sending face embedding to backend...")
    face_embedding = generate_dummy_embedding()
    embedding_data = {
        "person_id": person_id,
        "face_embedding": face_embedding,
        "source_image_url": "http://localhost/captured_face.jpg"
    }
    
    try:
        response = requests.post(f"{base_url}/face/embedding", json=embedding_data)
        if response.status_code == 200:
            result = response.json()
            print("✅ Face embedding sent successfully")
            print(f"   Message: {result['message']}")
        else:
            print(f"❌ Failed to send face embedding: {response.status_code}")
            print(f"   Error: {response.text}")
            return False
    except Exception as e:
        print(f"❌ Error sending face embedding: {e}")
        return False
    
    # Step 4: Verify the person was updated with face embedding
    print("\n4. Verifying final state...")
    try:
        response = requests.get(f"{base_url}/people")
        if response.status_code == 200:
            people = response.json()
            target_person = None
            for person in people:
                if person.get('person_id') == person_id:
                    target_person = person
                    break
            
            if target_person:
                print(f"🎉 Verification successful!")
                print(f"   Name: {target_person['name']}")
                print(f"   Relationship: {target_person['relationship']}")
                print(f"   Face embeddings: {len(target_person.get('face_embeddings', []))}")
                if len(target_person.get('face_embeddings', [])) > 0:
                    print("   🎉 Person successfully identified with face embedding!")
                    # Show first few values of the embedding
                    first_embedding = target_person['face_embeddings'][0]
                    print(f"   First few embedding values: {first_embedding['vector'][:5]}")
                    return True
                else:
                    print("   ⚠️  Face embedding not found in person record")
                    return False
            else:
                print("❌ Person not found after update")
                return False
        else:
            print(f"❌ Error getting people list: {response.status_code}")
            return False
    except Exception as e:
        print(f"❌ Error verifying update: {e}")
        return False

if __name__ == "__main__":
    print("Starting face embedding test...")
    success = test_face_embedding()
    if success:
        print("\n✅ Face embedding test completed successfully!")
    else:
        print("\n❌ Face embedding test failed!")